### ISSUE TITLE
Tasks state coming out from the response due to creating a blueprint is always new. 

### ISSUE THREAD

**Issue by john-kheir** [zero-os/0-robot#194]
Tasks state according to the below code is always in new state even though the tasks are already done
```
response, _ = client.api.blueprints.ExecuteBlueprint(data)

In [138]: response.tasks
Out[138]: 
[<JumpScale9Zrobot.clients.zerorobot.client.Task.Task at 0x7f41a0c5b4e0>,
 <JumpScale9Zrobot.clients.zerorobot.client.Task.Task at 0x7f41a0c5b518>,
 <JumpScale9Zrobot.clients.zerorobot.client.Task.Task at 0x7f41a0c5b550>,
 <JumpScale9Zrobot.clients.zerorobot.client.Task.Task at 0x7f41a0c5b588>,
 <JumpScale9Zrobot.clients.zerorobot.client.Task.Task at 0x7f41a0c5b5c0>]

In [139]: t4 = response.tasks[4]

In [140]: t4.state
Out[140]: <EnumTaskState.new: 'new'>
```

**Comment by zaibon** [comment]
Since this is a rest API, the state contain in the response is the state of the task when the response is sent. So new is correct.
But in this case, I state might not be a useful information to have in this response. The only point of having a list of tasks in the response is that the client can then use GetTask to follow the progress of the task state over time.

So maybe removing the state in this reponse would prevent this confusion.
